var str1 = "안녕하세요";
var num1 = 333;
var num2 = 1;
num1 = 5;
console.log(str1);
console.log(num1 + num2);
console.log("------------------------------------------");
var arrl = [2, 3, 4, 5, 6];
var arr2 = [2, 3, 4, 5, 6];
console.log(arrl);
console.log("------------------------------------------");
var bok = true;
console.log(bok);
